default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5


development:
  <<: *default
  database: scarf_shop_development

test:
  <<: *default
  database: scarf_shop_test

production:
  <<: *default
  database: scarf_shop_production
  username: deploy
