# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4648a20df0e326f0a289a7b08771152a732aa372181b55384fd988a833c86c06dc191019da104048089081304a9d3ae2f5b887558cfa36681bfabc743762ce8f

test:
  secret_key_base: cdf1637158c8361093dbba4fa791c5ac60f252d446710b18f833af8b736763f3f407c9c625e3310ccdf182e3f1990aa38b00e4e17d4193afcd28571308025139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
